FROM 263386586431.dkr.ecr.us-east-2.amazonaws.com/tibco-bwce:2.9.0_hma
ADD com.imperialdade.proofofdelivery.application/target/com.imperialdade.proofofdelivery.application_1.0.0.ear /
COPY cacerts /tmp/
