FROM 263386586431.dkr.ecr.us-east-2.amazonaws.com/tibco-bwce:2.9.0_hma
ADD com.imperialdade.aplus.apt.order.application/target/com.imperialdade.aplus.apt.order.application_1.0.0.ear .
COPY cacerts /tmp/
COPY Order_XSLTTransform.xslt /tmp/
