<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2023sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://com.imperialdade/schema/canonical/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="ns0 xs fn">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var7_CustomerOrder" as="node()?" select="ns0:CustomerOrder"/>
		<deliverOrderElement xmlns="http://tns.tibco.com/bw/json/1672935689456">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'http://tns.tibco.com/bw/json/1672935689456 file:///C:/Users/ngollapa/Desktop/spy/15032023/targetfile.xsd'"/>
			<CustomerOrder>
				<xsl:for-each select="$var7_CustomerOrder">
					<xsl:variable name="var3_Header" as="node()" select="ns0:Header"/>
					<Header>
						<CustomerID>
							<xsl:sequence select="xs:string(fn:string($var3_Header/ns0:CustomerID))"/>
						</CustomerID>
						<CustomerOrderID>
							<xsl:sequence select="xs:string(fn:string($var3_Header/ns0:CustomerOrderID))"/>
						</CustomerOrderID>
						<OrderDate>
							<xsl:sequence select="xs:string(fn:format-date(xs:date(fn:string($var3_Header/ns0:OrderDate)),'[Y0001][M01][D01]'))"/>
						</OrderDate>
						<xsl:variable name="var2_Shipment" as="node()" select="$var3_Header/ns0:Shipment"/>
						<Shipment>
							<ShipToID>
								<xsl:sequence select="xs:string(fn:string($var2_Shipment/ns0:ShipToID))"/>
							</ShipToID>
							<xsl:variable name="var1_ShipToAddress" as="node()" select="$var2_Shipment/ns0:ShipToAddress"/>
							<ShipToAddress>
								<Contact>
									<Name>
										<xsl:sequence select="fn:string($var1_ShipToAddress/ns0:Contact/ns0:Name)"/>
									</Name>
								</Contact>
								<xsl:for-each select="$var1_ShipToAddress/ns0:AddressLine">
									<AddressLine>
										<xsl:sequence select="fn:string(.)"/>
									</AddressLine>
								</xsl:for-each>
								<City>
									<xsl:sequence select="fn:string($var1_ShipToAddress/ns0:City)"/>
								</City>
								<State>
									<xsl:sequence select="fn:string($var1_ShipToAddress/ns0:State)"/>
								</State>
								<ZipCode>
									<xsl:sequence select="xs:string(xs:integer(fn:string($var1_ShipToAddress/ns0:ZipCode)))"/>
								</ZipCode>
							</ShipToAddress>
							<RequestedShipDate>
								<xsl:sequence select="xs:string(fn:format-date(xs:date(fn:string($var2_Shipment/ns0:RequestedShipDate)),'[Y0001][M01][D01]'))"/>
							</RequestedShipDate>
						</Shipment>
						<CustomerPO>
							<xsl:sequence select="fn:string($var3_Header/ns0:CustomerPO)"/>
						</CustomerPO>
					</Header>
				</xsl:for-each>
				<xsl:for-each select="$var7_CustomerOrder/ns0:Details">
					<Details>
						<CustomerItemID>
							<xsl:sequence select="fn:string(./ns0:CustomerItemID)"/>
						</CustomerItemID>
						<LineNumber>
							<xsl:sequence select="fn:string(./ns0:OrderLineID)"/>
						</LineNumber>
						<xsl:variable name="var5_Item" as="node()" select="ns0:Item"/>
						<Item>
							<ID>
								<xsl:sequence select="xs:string(fn:string($var5_Item/ns0:ID))"/>
							</ID>
							<xsl:for-each select="$var5_Item/ns0:Description">
								<Description>
									<xsl:sequence select="fn:string(.)"/>
								</Description>
							</xsl:for-each>
							<xsl:variable name="var4_UnitPrice" as="node()" select="$var5_Item/ns0:UnitPrice"/>
							<UnitPrice>
								<CurrencyCode>
									<xsl:sequence select="fn:string($var4_UnitPrice/ns0:CurrencyCode)"/>
								</CurrencyCode>
								<Value>
									<xsl:sequence select="xs:string(xs:decimal(fn:string($var4_UnitPrice/ns0:Value)))"/>
								</Value>
							</UnitPrice>
							<Rebate>
								<xsl:for-each select="ns0:ContractID">
									<ContractNumber>
										<xsl:sequence select="fn:string(.)"/>
									</ContractNumber>
								</xsl:for-each>
								<xsl:for-each select="ns0:ContractCost">
									<ContractCost>
										<xsl:sequence select="fn:string(ns0:Value)"/>
									</ContractCost>
								</xsl:for-each>
							</Rebate>
						</Item>
						<xsl:variable name="var6_OriginalOrderQuantity" as="node()" select="ns0:OriginalOrderQuantity"/>
						<OriginalOrderQuantity>
							<Quantity>
								<xsl:sequence select="xs:string(xs:decimal(fn:string($var6_OriginalOrderQuantity)))"/>
							</Quantity>
							<UOM>
								<xsl:sequence select="fn:string($var6_OriginalOrderQuantity/@unitCode)"/>
							</UOM>
						</OriginalOrderQuantity>
					</Details>
				</xsl:for-each>
			</CustomerOrder>
		</deliverOrderElement>
	</xsl:template>
</xsl:stylesheet>
