FROM 263386586431.dkr.ecr.us-east-2.amazonaws.com/tibco-bwce:2.9.0_hma
ADD com.imperialdade.sx.nichols.integration.application/target/com.imperialdade.sx.nichols.integration.application_1.0.0.ear .
COPY cacerts /tmp/